=== Labs64/NetLicensingClient-java/NetLicensingClient/src/main/resources/schema/netlicensing-context-2.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
            xmlns="http://netlicensing.labs64.com/schema/context"
            targetNamespace="http://netlicensing.labs64.com/schema/context"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:import namespace="http://www.w3.org/2000/09/xmldsig#"
                schemaLocation="http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd" />

    <xsd:element name="netlicensing">
        <xsd:annotation>
            <xsd:documentation>Service response root element</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="ds:Signature" minOccurs="0" maxOccurs="1">
                    <xsd:annotation>
                        <xsd:documentation>XML Signature element.</xsd:documentation>
                    </xsd:annotation>
                </xsd:element>
                <xsd:element name="agentSigning" minOccurs="0" maxOccurs="1">
                    <xsd:annotation>
                        <xsd:documentation>Security metadata for a response signed by an offline Agent.</xsd:documentation>
                    </xsd:annotation>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="certificate" type="xsd:string" />
                            <xsd:element name="publicKey" type="xsd:string" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="infos" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:annotation>
                            <xsd:documentation>Collection of the infos for the caller (information, warnings, errors
                                etc.)
                            </xsd:documentation>
                        </xsd:annotation>
                        <xsd:sequence>
                            <xsd:element name="info" type="info" maxOccurs="unbounded" minOccurs="0" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="items" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:annotation>
                            <xsd:documentation>Collection of the items</xsd:documentation>
                        </xsd:annotation>
                        <xsd:sequence>
                            <xsd:element name="item" type="item" maxOccurs="unbounded" minOccurs="0" />
                        </xsd:sequence>
                        <xsd:attribute name="pagenumber" type="xsd:string" use="optional">
                            <xsd:annotation>
                                <xsd:documentation>Page number</xsd:documentation>
                            </xsd:annotation>
                        </xsd:attribute>
                        <xsd:attribute name="itemsnumber" type="xsd:string" use="optional">
                            <xsd:annotation>
                                <xsd:documentation>Items number on page</xsd:documentation>
                            </xsd:annotation>
                        </xsd:attribute>
                        <xsd:attribute name="totalpages" type="xsd:string" use="optional">
                            <xsd:annotation>
                                <xsd:documentation>Total pages of the list</xsd:documentation>
                            </xsd:annotation>
                        </xsd:attribute>
                        <xsd:attribute name="totalitems" type="xsd:string" use="optional">
                            <xsd:annotation>
                                <xsd:documentation>Total items of the list</xsd:documentation>
                            </xsd:annotation>
                        </xsd:attribute>
                        <xsd:attribute name="hasnext" type="xsd:string" use="optional">
                            <xsd:annotation>
                                <xsd:documentation>Shows if page has a next page</xsd:documentation>
                            </xsd:annotation>
                        </xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="id" type="id_type" use="optional">
                <xsd:annotation>
                    <xsd:documentation>Request unique identifier.</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="ttl" type="xsd:dateTime" use="optional">
                <xsd:annotation>
                    <xsd:documentation>Time To Live - time stamp that determines the validity span of the response.
                        If not provided, the response should not be cached.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="info">
        <xsd:annotation>
            <xsd:documentation>Info element delivers all service messages to the caller</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="id" type="xsd:string" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>Info element unique identifier (can be info or error code)
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="type" type="info_enum" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>Info element type (error, warning, info)</xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="item">
        <xsd:annotation>
            <xsd:documentation>Item element describes a single business entity (product, license etc.)
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Simple property direct item element</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="list" type="list" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Group of properties or other lists</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="type" type="xsd:string" use="required">
            <xsd:annotation>
                <xsd:documentation>Item type description (usually a business entity class name)</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="property">
        <xsd:annotation>
            <xsd:documentation>A property element represents all base and custom properties for used at business
                entities
            </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="name" type="xsd:string" use="required">
                    <xsd:annotation>
                        <xsd:documentation>A property element name attribute describes uniquely every property.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="list">
        <xsd:annotation>
            <xsd:documentation>A list element groups properties and nested lists</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Simple property list element</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="list" type="list" minOccurs="0" maxOccurs="unbounded">
                <xsd:annotation>
                    <xsd:documentation>Nested list</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required">
            <xsd:annotation>
                <xsd:documentation>Name of the list. Identifies this list if multiple lists are present at the same
                    level.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="id_type">
        <xsd:annotation>
            <xsd:documentation>Base identifier type. Can be any string 1-255 characters length.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
            <xsd:maxLength value="255" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="info_enum">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="error" />
            <xsd:enumeration value="warning" />
            <xsd:enumeration value="info" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-bundle-obtain.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items pagenumber="0" itemsnumber="3" totalpages="1" totalitems="3" hasnext="false">
        <item type="License">
            <property name="number">L001-TEST</property>
            <property name="active">true</property>
            <property name="name">TimeVolume license</property>
            <property name="price">10.00</property>
            <property name="currency">EUR</property>
            <property name="hidden">false</property>
            <property name="licenseeNumber">LE001-TEST</property>
            <property name="licenseTemplateNumber">LT001-TEST</property>
            <property name="timeVolume">30</property>
            <property name="parentFeature">LC001-PARENT</property>
            <property name="startDate">2014-07-07T21:30:45.574Z</property>
        </item>
        <item type="License">
            <property name="number">L002-TEST</property>
            <property name="active">false</property>
            <property name="name">Test License 2</property>
            <property name="price">13.00</property>
            <property name="currency">EUR</property>
            <property name="hidden">false</property>
            <property name="licenseeNumber">LE001-TEST</property>
            <property name="licenseTemplateNumber">LT001-TEST</property>
            <property name="timeVolume">30</property>
            <property name="parentFeature">LC002-PARENT</property>
            <property name="startDate">2014-07-07T08:10:12.449Z</property>
        </item>
        <item type="License">
            <property name="number">L003-TEST</property>
            <property name="active">true</property>
            <property name="name">Test License 3</property>
            <property name="price">15.00</property>
            <property name="currency">EUR</property>
            <property name="hidden">false</property>
            <property name="licenseeNumber">LE001-TEST</property>
            <property name="licenseTemplateNumber">LT001-TEST</property>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-notification-update.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items>
        <item type="Notification">
            <property name="number">N002-TEST</property>
            <property name="active">false</property>
            <property name="name">Notification 2</property>
            <property name="events">LICENSEE_CREATED</property>
            <property name="protocol">WEBHOOK</property>
            <property name="endpoint">http://www.test.test</property>
            <property name="payload">${event}</property>
            <property name="CustomProperty">Test Value</property>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-bundle-list.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items pagenumber="0" itemsnumber="3" totalpages="1" totalitems="3" hasnext="false">
        <item type="Bundle">
            <property name="number">B001-TEST</property>
            <property name="active">true</property>
            <property name="name">Bundle 1</property>
            <property name="description">Description 1</property>
            <property name="price">10</property>
            <property name="currency">EUR</property>
            <property name="licenseTemplatesNumbers">LT001-TEST,LT002-TEST</property>
        </item>
        <item type="Bundle">
            <property name="number">B002-TEST</property>
            <property name="active">true</property>
            <property name="name">Bundle 2</property>
            <property name="description">Description 2</property>
            <property name="price">20</property>
            <property name="currency">USD</property>
            <property name="licenseTemplatesNumbers">LT003-TEST,LT004-TEST</property>
        </item>
        <item type="Bundle">
            <property name="number">B003-TEST</property>
            <property name="active">true</property>
            <property name="name">Bundle 3</property>
            <property name="description">Description 3</property>
            <property name="price">30</property>
            <property name="currency">EUR</property>
            <property name="licenseTemplatesNumbers">LT005-TEST,LT006-TEST</property>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-token-list.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items pagenumber="0" itemsnumber="3" totalpages="1" totalitems="3" hasnext="false">
        <item type="Token">
            <property name="number">08b66094-a5c4-4c93-be71-567e982d9428</property>
            <property name="active">true</property>
            <property name="expirationTime">2014-06-30T12:47:56.067Z</property>
            <property name="tokenType">SHOP</property>
            <property name="shopURL">
                https://go.netlicensing.io/shop/v2/?shoptoken=08b66094-a5c4-4c93-be71-567e982d9428
            </property>
            <property name="licenseeNumber">ITEST-ABC-DEMO</property>
            <property name="vendorNumber">VDEMO</property>
        </item>
        <item type="Token">
            <property name="number">092da8ce-126e-4602-91d8-5c41903846d3</property>
            <property name="active">true</property>
            <property name="expirationTime">2014-07-22T23:07:46.742Z</property>
            <property name="tokenType">DEFAULT</property>
            <property name="vendorNumber">VDEMO</property>
        </item>
        <item type="Token">
            <property name="number">0c924950-de52-4581-b2dc-5031fa04ef29</property>
            <property name="active">true</property>
            <property name="expirationTime">2014-08-06T13:18:05.982Z</property>
            <property name="tokenType">APIKEY</property>
            <property name="vendorNumber">VDEMO</property>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-licensee-validate-offline.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items>
        <item type="Licensee">
            <property name="number">L001-TEST</property>
        </item>
        <item type="ProductModuleValidation">
            <property name="productModuleNumber">M001-TEST</property>
            <property name="licensingModel">FeatureWithTimeVolume</property>
            <property name="productModuleName">Test module</property>
            <list name="LIST1">
                <property name="valid">true</property>
                <property name="expires">2014-08-06T21:30:45.574Z</property>
                <property name="warningLevel">GREEN</property>
            </list>
            <list name="LIST2">
                <property name="valid">true</property>
                <property name="expires">2014-08-06T21:30:45.186Z</property>
                <property name="warningLevel">GREEN</property>
            </list>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-notification-list.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items pagenumber="0" itemsnumber="3" totalpages="1" totalitems="3" hasnext="false">
        <item type="Notification">
            <property name="number">N001-TEST</property>
            <property name="active">true</property>
            <property name="name">Notification 1</property>
            <property name="events">LICENSEE_CREATED</property>
            <property name="protocol">WEBHOOK</property>
            <property name="endpoint">http://www.test1.test</property>
            <property name="payload">${event}</property>
        </item>
        <item type="Notification">
            <property name="number">N002-TEST</property>
            <property name="active">true</property>
            <property name="name">Notification 2</property>
            <property name="events">LICENSE_CREATED</property>
            <property name="protocol">WEBHOOK</property>
            <property name="endpoint">http://www.test2.test</property>
            <property name="payload">${event.timestamp}</property>
        </item>
        <item type="Notification">
            <property name="number">N003-TEST</property>
            <property name="active">true</property>
            <property name="name">Notification 3</property>
            <property name="events">LICENSEE_CREATED</property>
            <property name="protocol">WEBHOOK</property>
            <property name="endpoint">http://www.test3.test</property>
            <property name="payload">${event.data}</property>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-bundle-update.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items>
        <item type="LicenseTemplate">
            <property name="number">B002-TEST</property>
            <property name="active">true</property>
            <property name="name">Bundle 2</property>
            <property name="description">Description 2</property>
            <property name="price">20.00</property>
            <property name="currency">USD</property>
            <property name="licenseTemplateNumbers">LT003-TEST,LT004-TEST</property>
        </item>
    </items>
</netlicensing>

=== Labs64/NetLicensingClient-java/NetLicensingClient/src/test/resources/mock/netlicensing-notification-get.xml
<netlicensing xmlns="http://netlicensing.labs64.com/schema/context"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://netlicensing.labs64.com/schema/context
                                  https://go.netlicensing.io/schema/context/netlicensing-context-2.1.xsd">
    <items>
        <item type="Notification">
            <property name="number">N014-TEST</property>
            <property name="active">true</property>
            <property name="name">Notification 14</property>
            <property name="events">CREATE_LICENSEE,CREATE_LICENSE</property>
            <property name="type">WEBHOOK</property>
            <property name="url">http://www.test.test</property>
            <property name="payload">${event}</property>
            <property name="CustomProperty">CustomPropertyValue</property>
        </item>
    </items>
</netlicensing>
